apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: org2-ca
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hyperledger
        role: ca
        org: org2
        name: org2-ca
    spec:
      containers:
        - name: org2-ca
          image: hyperledger/fabric-ca:latest
          env:
            - name: FABRIC_CA_HOME
              value: /etc/hyperledger/fabric-ca-server
            - name: FABRIC_CA_SERVER_CA_NAME
              value: org2.ca.example.com
            - name: FABRIC_CA_SERVER_TLS_ENABLED
              value: "false"
            - name: FABRIC_CA_SERVER_CA_CERTFILE
              value: /etc/hyperledger/fabric-ca-server-config/ca.org2.example.com-cert.pem
            - name: FABRIC_CA_SERVER_CA_KEYFILE
              value: /etc/hyperledger/fabric-ca-server-config/ef6e6a2ce23664dbfa50c1f27311bd5e143b9ac3733ab3ea5725523729f971bd_sk
          ports:
            - containerPort: 7054
          command: ["sh"]
          args: ["-c", "fabric-ca-server start -b admin:adminpw"]
          volumeMounts:
            - mountPath: /etc/hyperledger/fabric-ca-server-config
              name: cert-pv
              subPath: peerOrganizations/org2.example.com/ca/
          resources:
            requests:
              memory: 128M
              cpu: "0.05"
            limits:
              memory: 256M
              cpu: "0.1"
      volumes:
        - name: cert-pv
          persistentVolumeClaim:
            claimName: cert-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: org2-ca
spec:
  selector:
    app: hyperledger
    role: ca
    org: org2
    name: org2-ca
  type: NodePort
  ports:
    - name: endpoint
      protocol: TCP
      port: 7054
      targetPort: 7054
      nodePort: 30101
