apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: org1-ca
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hyperledger
        role: ca
        org: org1
        name: org1-ca
    spec:
      containers:
        - name: org1-ca
          image: hyperledger/fabric-ca:1.4.0
          env:
            - name: FABRIC_CA_HOME
              value: /etc/hyperledger/fabric-ca-server
            - name: FABRIC_CA_SERVER_CA_NAME
              value: org1.ca.example.com
            - name: FABRIC_CA_SERVER_TLS_ENABLED
              value: "false"
            - name: FABRIC_CA_SERVER_CA_CERTFILE
              value: /etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
            - name: FABRIC_CA_SERVER_CA_KEYFILE
              value: /etc/hyperledger/fabric-ca-server-config/bfafe0afe27f694a5f1c024505c0a51a95c848443b5c69739ae3465eb7c5afce_sk
          ports:
            - containerPort: 7054
          command: ["sh"]
          args: ["-c", "fabric-ca-server start -b admin:adminpw"]
          volumeMounts:
            - mountPath: /etc/hyperledger/fabric-ca-server-config
              name: cert-pv
              subPath: peerOrganizations/org1.example.com/ca/
          resources:
            requests:
              memory: 128M
              cpu: "0.05"
            limits:
              memory: 256M
              cpu: "0.1"
      volumes:
        - name: cert-pv
          persistentVolumeClaim:
            claimName: cert-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: org1-ca
spec:
  selector:
    app: hyperledger
    role: ca
    org: org1
    name: org1-ca
  type: NodePort
  ports:
    - name: endpoint
      protocol: TCP
      port: 7054
      targetPort: 7054
      nodePort: 30100
