apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: N/A
  name: ca
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hyperledger
        role: ca
        org: N/A
        name: ca
    spec:
      containers:
        - name: ca
          image: hyperledger/fabric-ca:latest
          env:
            - name: FABRIC_CA_HOME
              value: /etc/hyperledger/fabric-ca-server
          ports:
            - containerPort: 7054
          command: ["sh"]
          args: ["-c", N/A]
          volumeMounts:
            - mountPath: /etc/hyperledger/fabric-ca-server-config
              name: certificaate
              subPath: N/A
       volumes:
        - name: certificate
          persistentVolumeClaim:
            claimName: N/A   
          
apiVersion: v1
kind: Service
metadata:
  namespace: N/A
  name: ca
spec:
  selector:
    app: hyperledger
    role: ca
    org: N/A
    name: ca
type: NodePort
ports:
  - name: endpoint
    protocol: TCP
    port: 7054
    targetPort: 7054
    nodePort: N/A