apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: org1-peer
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hyperledger
        role: peer
        org: org1
        peer-id: peer0
    spec:
      containers:
        - name: org1-peer0-couchdb
          image: hyperledger/fabric-couchdb:0.4.15
          ports:
            - containerPort: 5984
          resources:
            requests:
              memory: 128M
              cpu: "0.05"
            limits:
              memory: 256M
              cpu: "0.1"

        - name: dind
          image: docker:18.09.9-dind
          securityContext:
            privileged: true
          volumeMounts:
            - name: dind-storage
              mountPath: /var/lib/docker

        - name: org1-peer0
          image: hyperledger/fabric-peer:1.4.1
          env:
            - name: CORE_LEDGER_STATE_STATEDATABASE
              value: "CouchDB"
            - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
              value: "localhost:5984"
            - name: CORE_VM_ENDPOINT
              value: "tcp://localhost:2375"
            - name: CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE
              value: "bridge"
            - name: GODEBUG
              value: "netdns=go"
            - name: FABRIC_LOGGING_SPEC
              value: "info"
            - name: CORE_PEER_LOCALMSPID
              value: "Org1MSP"
            - name: CORE_PEER_ID
              value: "peer0.org1.example.com"
            - name: CORE_PEER_MSPCONFIGPATH
              value: /etc/hyperledger/msp
            - name: CORE_PEER_ADDRESS
              value: "peer0.org1.example.com:7051"
            - name: CORE_PEER_ADDRESSAUTODETECT
              value: "true"
          ports:
            - containerPort: 7051
            - containerPort: 7053
          command: ["peer"]
          args: ["node", "start"]
          volumeMounts:
            - mountPath: /etc/hyperledger/msp
              name: cert-pv
              subPath: peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp
            - mountPath: /etc/hyperledger/msp/users
              name: cert-pv
              subPath: peerOrganizations/org1.example.com/users
            - mountPath: /var/hyperledger/production/
              name: peer0-org1-pv
            - mountPath: /host/var/run/docker.sock
              name: docker-socket
          resources:
            requests:
              memory: 256M
              cpu: "0.2"
            limits:
              memory: 512M
              cpu: "0.5"
      volumes:
        - name: cert-pv
          persistentVolumeClaim:
            claimName: cert-pvc
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
        - name: dind-storage
          emptyDir: {}
        - name: peer0-org1-pv
          persistentVolumeClaim:
            claimName: peer0-org1-pvc
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: org1-peer
spec:
  selector:
    app: hyperledger
    role: peer
    org: org1
    peer-id: peer0
  type: NodePort
  ports:
    - name: peer-endpoint
      protocol: TCP
      port: 7051
      targetPort: 7051
      nodePort: 30110
    - name: listener-endpoint
      protocol: TCP
      port: 7053
      targetPort: 7053
      nodePort: 30111
