apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: default
  name: cert-pv
spec:
  capacity:
    storage: 500M
  storageClassName: default
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/sda1/mounted/crypto-config # change to path you want 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: cert-pvc
spec:
  storageClassName: default
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10M