OrdererOrgs:
  - Name: OrdererOrg
    Domain: orderer.example.com
    Template: 
      Count: 1

PeerOrgs:
  - Name: Org1
    Domain: org2.example.com
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Org2
    Domain: org2.example.com
    Template:
      Count: 1
    Users:
      Count: 1